											// rex macro
S	[\+\-]?
N	[0-9]+
%%
#.*						{}					// drop comments

\?\=					TOC(Op,ASS)			// assert ?=

\@						TOC(Op,AT)

\+						TOC(Op,ADD)
\-						TOC(Op,SUB)
\*						TOC(Op,MUL)
\/						TOC(Op,DIV)
\^						TOC(Op,POW)

{N}(\.{N})?[eE]{S}{N}	TOC(Num,NUM)		// number
({N})?\.{N}				TOC(Num,NUM)
{N}\.({N})?				TOC(Num,NUM)
{N}						TOC(Int,INT)		// integer


\n						TOC(Op,EOL)			// end of line
